apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: litchifrontend # You'll need to manually type this out. The environment variable won't work
spec:
  replicas: 2
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: litchifrontend
    spec:     # pod spec                  
      containers: 
      - name: litchifrontend 
        image: gcr.io/litchifrontend/lambda-backend-devops:v1  # image we pushed
        ports:
        - containerPort: 8080